[workspace]
members = [
    "bindings",
    "kloader",
    "kernel",
]
resolver = "2"

[profile.dev]
panic = "abort"
overflow-checks = false
opt-level = 2
debug = true
lto = "fat"

[profile.release]
panic = "abort"
overflow-checks = false
opt-level = 3
lto = "fat"
