[workspace]
members = [
    "bindings",
    "kloader",
    "kernel", 
    "stdlib",
    "vm",
]
resolver = "2"

[profile.dev]
panic = "abort"
overflow-checks = false
opt-level = 2
debug = true

[profile.release]
panic = "abort"
overflow-checks = false
opt-level = 3
