[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
bindings = { path = "../bindings" }

once_cell = { version = "1.20.2" }
lazy_static = "1.5.0"
spin = "0.9.8"
